-- ============================================================
-- [마이그레이션] TMDB OTT 캘린더 자동 연동 (2026)
--
-- ⚠️ 운영 DB의 contents 테이블은 camelCase 컬럼명을 씁니다.
--    → 새 컬럼도 큰따옴표로 감싼 camelCase 로 추가합니다.
--    Supabase 대시보드 → SQL Editor 에 아래를 붙여넣고 실행하세요.
--
-- 설계 메모: 별도 calendar_contents 테이블을 새로 만들지 않고
--   기존 contents 테이블을 확장합니다. 캘린더 항목이 리뷰/수다방/찜/내피드와
--   contents.id 로 연결돼 있어(수다방 들어가기 등) 테이블을 분리하면 연동이 깨집니다.
--   중복 방지 고유키는 기존 기본키 id 를 그대로 사용합니다.
--     · 영화     : tmdb-mv-{tmdbId}
--     · 시리즈   : tmdb-dr-{tmdbId}
--     · 시즌     : tmdb-dr-{tmdbId}-s{seasonNumber}
--   → sync 스크립트가 이 규칙으로 id 를 만들어 upsert(on_conflict=id) 하므로
--     중복이 생기지 않습니다. (스펙의 content_key ≡ 여기서는 id)
-- ============================================================

-- ── 1) OTT/캘린더 메타 컬럼 ────────────────────────────────
alter table public.contents add column if not exists "tmdbId"             bigint;
alter table public.contents add column if not exists "mediaType"          text;    -- 'movie' | 'tv'
alter table public.contents add column if not exists "eventType"          text;    -- 'movie_release' | 'series_release' | 'season_release'
alter table public.contents add column if not exists "seasonNumber"       integer;
alter table public.contents add column if not exists "originalTitle"      text;
alter table public.contents add column if not exists "backdropUrl"        text;

-- 실제 국내 공개일을 사람이 고쳤을 때 자동 동기화가 덮어쓰지 않도록 하는 필드
alter table public.contents add column if not exists "manualReleaseDate"  date;
alter table public.contents add column if not exists "manualOverride"     boolean not null default false;

-- 'kr_digital' | 'kr_theatrical' | 'tmdb_release_date' | 'tmdb_first_air_date'
-- | 'tmdb_season_air_date' | 'tmdb_estimated' | 'manual'
alter table public.contents add column if not exists "releaseDateSource"  text;

-- 이 작품을 제공하는 OTT 목록 (여러 OTT면 배열에 합쳐 저장)
--   [{ providerId, providerName, logoPath, monetizationType:'flatrate' }, ...]
alter table public.contents add column if not exists "providers"          jsonb not null default '[]'::jsonb;

alter table public.contents add column if not exists "voteAverage"        numeric;
alter table public.contents add column if not exists "voteCount"          integer;
alter table public.contents add column if not exists "tmdbUrl"            text;
alter table public.contents add column if not exists "source"             text;    -- 'tmdb'
alter table public.contents add column if not exists "region"             text;    -- 'KR'
alter table public.contents add column if not exists "hidden"             boolean not null default false;
alter table public.contents add column if not exists "syncedAt"           timestamptz;

-- eventType 유효값 제약 (있어도/없어도 무해)
alter table public.contents drop constraint if exists contents_event_type_check;
alter table public.contents add  constraint contents_event_type_check
  check ("eventType" is null or "eventType" in ('movie_release','series_release','season_release'));

-- ── 2) 조회 최적화 인덱스 ──────────────────────────────────
create index if not exists idx_contents_release   on public.contents ("releaseDate");
create index if not exists idx_contents_media      on public.contents ("mediaType");
create index if not exists idx_contents_tmdb       on public.contents ("tmdbId");
create index if not exists idx_contents_hidden     on public.contents ("hidden");
-- providers 배열 내부 검색(특정 OTT 필터)용 GIN
create index if not exists idx_contents_providers  on public.contents using gin ("providers");

-- ── 3) 동기화 로그 테이블 ──────────────────────────────────
create table if not exists public.sync_logs (
  id           bigint generated by default as identity primary key,
  job          text not null default 'tmdb-ott',
  "startedAt"  timestamptz not null default now(),
  "finishedAt" timestamptz,
  status       text not null default 'running',   -- 'running' | 'success' | 'failed'
  mode         text,                              -- 'full' | 'incremental'
  "rangeStart" date,
  "rangeEnd"   date,
  stats        jsonb not null default '{}'::jsonb,
  errors       jsonb not null default '[]'::jsonb
);
create index if not exists idx_sync_logs_started on public.sync_logs ("startedAt" desc);

-- RLS: 로그는 조회는 공개(관리자 대시보드용), 쓰기는 service_role(sync 스크립트)만.
alter table public.sync_logs enable row level security;
drop policy if exists sync_logs_read on public.sync_logs;
create policy sync_logs_read on public.sync_logs for select using (true);
-- (service_role 은 RLS 를 우회하므로 별도 insert 정책 불필요)

-- 확인용:
-- select "releaseDate", "mediaType", title, "releaseDateSource", "providers"
--   from public.contents where source = 'tmdb' order by "releaseDate";
